const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~VVwgFDRB#JC3IT3_ACx6CO6qyWQWbmIUsKl3ca9o1CFgamolDuME"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
